apiVersion: v1
kind: Service
metadata:
  name: shipping-service # Nama service
  labels: 
    app: shipping-service # Memilih pod yang akan menjadi target service
spec:
  type: NodePort # Menggunakan type NodePort
  ports:
  - port: 3001 # Port service yang akan diakses
  selector:
    app: shipping-service # Memilih pod yang akan menjadi target service