apiVersion: v1 # Versi API Kubernetes dan jenis objek yang akan digunakan (Secret)
kind: Secret # Jenis objek Kubernetes yang akan dibuat (Secret)
metadata:
  name: mongo-credentials  # Nama dari Secret
type: opaque # Jenis Secret yang digunakan
data:
  MONGO_ROOT_USERNAME: YWRtaW4= # Username MongoDB
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== # Password MongoDB
