apiVersion: v1 # Versi API Kubernetes dan jenis objek yang akan digunakan
kind: Service # Jenis objek Kubernetes yang akan dibuat

metadata:
  name: karsajobs-service # Nama Service yang akan dibuat
  labels:
     app: backend # Label yang ditetapkan untuk Service

spec:
  type: NodePort # Jenis Service, dalam hal ini, ClusterIP yang memberikan alamat IP internal Kubernetes
  ports:
  - port: 8080 # Port yang akan di-expose di dalam Service
  selector:
    app: backend # Selector untuk memilih pod yang ingin diasosiasikan dengan Service
