apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service-internal # Nama service yang akan dibuat
  labels:
    app: rabbitmq # Label yang digunakan
spec:
  ports:
  - port: 5672 # Port yang digunakan oleh service
    protocol: TCP # Menggunakan TCP protocol
  #type: ClusterIP
  selector:
    app: rabbitmq # Selector app yaitu rabbitmq