apiVersion: v1
kind: Service
metadata:
  name: order-service # Nama service
  labels: 
    app: order-service # Memilih pod yang akan menjadi target service
spec:
  type: NodePort # Menggunakan type NodePort
  ports:
  - port: 3000 # Port service yang akan diakses
  selector:
    app: order-service # Memilih pod yang akan menjadi target service